name: Sync to Ent Repo

on:
  workflow_dispatch:
  # UTC time scale down Runs at 00:00 Beijing time, Monday through Friday.
  schedule:
    - cron: '*/10 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Auth as Github App
        id: github-auth
        uses: zqdou/kraken-ent/.github/actions/github-app-get-token@main
        with:
          repositoryNames: '${{ github.event.repository.name }}'
          codePermission: write
          pullRequestPermission: write
          appID: '${{ secrets.SYNC_GITHUB_APP_ID }}'
          privateKey: '${{ secrets.SYNC_GITHUB_APP_PRIVATE_KEY }}'
          installationId: '${{ secrets.SYNC_GITHUB_APP_INSTALLATION_ID }}'
          
      - name: Checkout source repository        
        uses: actions/checkout@v4
        with:
          token: '${{steps.github-auth.outputs.github-token }}'
          fetch-depth: 0

      - name: pull from upstream repository
        env:
          GITHUB_TOKEN: '${{ steps.github-auth.outputs.github-token }}'
        run: |
          git config --global user.name "cloudnexus-gha-actions[bot]"
          git config --global user.email "57290432+cloudnexus-gha-actions[bot]@users.noreply.github.com"
          ls -al
          git remote add upstream https://github.com/zqdou/kraken.git
          git remote update
          git config --global merge.ours.driver true
          git merge ${{ env.ORIGINAL_REPO_NAME }}/main --allow-unrelated-histories -s ours
          git push origin $(git rev-parse --abbrev-ref HEAD)